### ISSUE TITLE
Missing v0.6.x tags

### ISSUE THREAD

**Issue by oliv3r** [uPesy/easyeda2kicad.py#102]
After v0.6.0 we see version bumps, but no tags for these bumps.

I think it is wise to retroactively add the tags to the correct commits and push those, which makes lives of packagers easier :)

v0.6.3 -> ea0aed712
v0.6.2 -> 81884172e
v0.6.1 -> 03ac33b02

**Comment by uPesy** [comment]
Thanks @oliv3r for this issue. I don't know why the tags are not pushed automatically as before. I did it manually.

**Comment by oliv3r** [comment]
@uPesy missing 0.7.0 and 0.8.0 tags now too :(

**Comment by vinicentus** [comment]
Yes, I think this should be reopened. I just noticed the same thing

**Comment by oliv3r** [comment]
@uPesy any update on this? or should I create a new issue?
