### ISSUE TITLE
Minor symbol issues and 3D model offset [LCSC C393942]

### ISSUE THREAD

**Issue by Bouni** [uPesy/easyeda2kicad.py#25]
Hi,

first of all, wonderful tool 🤩 

Added this switch:
![grafik](https://user-images.githubusercontent.com/948965/165329774-7284a06c-2842-4ec1-8192-587903e74c2e.png)

Thats the result in the Schematic:
![grafik](https://user-images.githubusercontent.com/948965/165330278-4fe5ff8d-0f43-4449-9077-4120891c33fb.png)

This is what esyEDA gives me:
![grafik](https://user-images.githubusercontent.com/948965/165330181-ade39de6-7db2-468c-af96-776f44e1bf9d.png)

The footprint looks good apart from minor artifacts:
![grafik](https://user-images.githubusercontent.com/948965/165330673-7da894af-a482-49c0-9e7d-32afbcadef77.png)

The 3D model is offset in Y and Z:
![grafik](https://user-images.githubusercontent.com/948965/165329726-a7ee25e5-632f-471d-a741-1b837f997db1.png)

**Comment by uPesy** [comment]
Thanks for pointing out these issues.
For the schematic, it's the 22 ? 
For the footprint, these dots are actually also on the easyeda footprint
![image](https://user-images.githubusercontent.com/61392244/166115304-188ae8ca-ece1-4b40-8b27-e8bc12278c4d.png)
I think it's for orientation.
For the 3D model, i know that there are issue offset on some 3D model, but i have not find wet a formula to fix the offset that works on all components.
I will try to fix that when i have time.

**Comment by Bouni** [comment]
I might stumbled upon something helpful!
If I use easyeda and add LCSC Part C393942, then in the PCB I click on the 3D Model text in the Properties sidebar `SW-SMD_TS24CA` I get a 3D viewer where I can see offsets:

![image](https://user-images.githubusercontent.com/948965/166698586-012c6ef6-4b31-483d-89db-5e0cb35181c0.png)

The data from the json `["packageDetail"]["dataStr"]["shape"] -> SVGNODE` is:

```
{
    "gId": "g1_outline",
    "nodeName": "g",
    "nodeType": 1,
    "layerid": "19",
    "attrs": {
        "c_width": "17.9134",
        "c_height": "14.1732",
        "c_rotation": "0,0,0",
        "z": "-1.5748",
        "c_origin": "3999.7563,2998.6197",
        "uuid": "739232e7e2bb4235a1eea61c76b19f50",
        "c_etype": "outline3D",
        "id": "g1_outline",
        "title": "SW-SMD_TS24CA",
        "layerid": "19",
        "transform": "scale(1) translate(0, 0)"
    },
    "childNodes": [
        {
            "gId": "g1_outline_line0",
            "nodeName": "polyline",
            "nodeType": 1,
            "attrs": {
                "fill": "none",
                "id": "g1_outline_line0",
                "c_shapetype": "line",
                "points": "3990.7997 2996.2575 3990.7997 2996.6512 3990.8784 2996.6512 3990.7997 2996.8481 3990.7997 2997.0449 3990.7997 3000.1945 3991.1934 3000.1945 3991.1934 2997.0449 3991.1934 2996.9268 3991.2327 2996.8481 3991.2721 2996.7693 3991.2721 2997.8717 3991.2721 3001.0607 3991.2721 3001.2181 3991.2721 3001.2575 3991.2721 3003.1079 3991.2721 3003.7378 3991.2721 3005.3126 3991.9808 3005.3126 3992.2563 3005.3126 3992.2563 3005.5882 3992.2563 3005.7063 3993.8311 3005.7063 3993.8311 3005.5882 3993.8311 3005.3126 3994.4217 3005.3126 3997.8863 3005.3126 3998.1618 3005.3126 3998.1618 3004.5252 3999.3036 3004.5252 4000.3666 3004.5252 4001.3114 3004.5252 4001.3114 3005.3126 4001.3508 3005.3126 4002.3744 3005.3126 4003.5949 3005.3126 4005.0516 3005.3126 4005.6421 3005.3126 4005.6421 3005.5882 4005.6421 3005.7063 4007.2169 3005.7063 4007.2169 3005.5882 4007.2169 3005.3126 4007.5319 3005.3126 4008.2012 3005.3126 4008.2012 3003.7378 4008.2012 3003.1079 4008.2012 3001.2575 4008.2012 3001.2181 4008.2012 3001.0607 4008.2012 2997.8717 4008.2012 2996.7693 4008.2406 2996.8481 4008.2799 2996.9268 4008.2799 2997.0449 4008.2799 3000.1945 4008.713 3000.1945 4008.713 2997.0449 4008.6736 2996.8481 4008.5949 2996.6512 4008.713 2996.6512 4008.713 2996.2575 4008.1225 2996.2575 4007.9256 2996.2575 4007.5319 2996.2575 4007.2169 2996.2575 4007.1382 2995.4701 4006.1146 2995.4701 4006.0358 2996.2575 4003.6736 2996.2575 4003.0437 2991.8481 4003.0437 2991.7693 4003.0044 2991.6906 4002.9256 2991.6119 4002.8862 2991.5725 4002.8075 2991.5725 4002.7681 2991.5331 4002.8469 2991.5725 4002.8075 2991.5725 4002.7288 2991.5331 4002.7681 2991.5331 4002.8075 2991.5725 4002.7681 2991.5725 4002.7288 2991.5331 4002.8075 2991.5725 4002.8075 2991.6119 4002.7681 2991.5725 4002.8075 2991.5725 4002.8469 2991.6119 4002.8075 2991.6119 4002.8075 2991.5725 4002.8862 2991.6119 4002.8469 2991.6119 4002.8075 2991.5725 4002.8862 2991.5725 4002.8862 2991.6119 4002.8075 2991.5725 4002.8469 2991.5725 4002.9256 2991.6119 4002.8862 2991.6119 4002.8862 2991.5725 4002.9256 2991.6119 4002.8469 2991.5725 4002.8862 2991.5725 3990.7997 2996.2575 3990.7997 2996.2575"
            }
        }
    ]
}
```

Width from the screenshot is 4.55mm which is `c_width * 10` in mil (179.134 / 39.37 = 4.55).
Height from the screenshot is 3.6mm which is `c_height * 10` in mil (141.732 / 39.37 = 3.6).
The same applies for the Z offset: -15.748 / 39.37 = -0.4

Unfortuantely I have not yet found out where the X and Y offsets are coming from ...

**Comment by uPesy** [comment]
Thanks for your researchs !
For the X and Y offsets, it maybe comes from `c_origin` array ?
And applying the `bbox` values of the footprint

**Comment by Bouni** [comment]
I think I found the solution (partially to be honest)

https://github.com/uPesy/easyeda2kicad.py/compare/dev...Bouni:3d-model-offsets?expand=1

With these changes, the 3d model for a couple of parts that previously had wrong offsets are working just fine:

**C393942**

![image](https://user-images.githubusercontent.com/948965/174738783-d64715da-b8ff-403e-95a2-cb7d6f7af434.png)

**C13453**

![image](https://user-images.githubusercontent.com/948965/174739149-eea91c23-e97c-4109-8cad-fbc4d557087d.png)

**C264374**

![image](https://user-images.githubusercontent.com/948965/174739859-ea7cad06-7154-4eb1-924a-5d60890d765f.png)


Unfortunately I found one that is still offset and I cannot see why 😭 

**C545708**

![image](https://user-images.githubusercontent.com/948965/174740903-c88c1038-9e96-4504-8881-9e7d8d0c997a.png)

**Comment by uPesy** [comment]
Thanks for your research !
For the last one it's maybe a rotation issue  ? from 180° ?
You can send a PR to dev branch, and i will merge it :)

**Comment by Bouni** [comment]
Done via PR #57 !

> For the last one it's maybe a rotation issue ? from 180° ?
It has 270° as rotation but actually needs 90° and it needs 3.5mm z offset:

![image](https://user-images.githubusercontent.com/948965/174771847-908da42d-734a-4254-9303-6c68568a6a75.png)

I simply don't get it why some parts work absolutely fine and others are just messed up 🤷🏽‍♂️

**Comment by Bouni** [comment]
This is what easyeda shows for that part:

![image](https://user-images.githubusercontent.com/948965/174772906-9f673d7e-79cc-445a-b013-9491b46b5e65.png)

**Comment by uPesy** [comment]
I have fixed the issue for the rotation.
But for the x, y, z offset, it's very tricky :/
