### ISSUE TITLE
Symbol and 3D model broken in 0.3.1

### ISSUE THREAD

**Issue by Bouni** [uPesy/easyeda2kicad.py#33]
I've just updated to 0.3.1 and it seems that the symbol (new .kicad_sym) as well as the 3D Model do no longer work!

`6.0.5` and `6.99` (latest nightly) both do not show a symbol nor the 3D Model but the fotprint is working.
I tested with C2040 as it is known to be working.

I found out that there is a Bracket to much, if I delete that it works.
```
(kicad_symbol_lib
  (version 20211014)
  (generator https://github.com/uPesy/easyeda2kicad.py)
) <--- This Bracket is to much !!
  (symbol "RP2040"
```

Why the .wrl file is not working is still unclear ...

**Comment by Bouni** [comment]
One note about the WRL model: I think if I remember correctly, KiCAD used to load your WRL files and show them correct, but various WRL viewers threw errors. Now its the same for the viewers but this time KiCAD won't show the model either.

I tested https://www.creators3d.com/online-viewer, https://imagetostl.com/view-wrl-online and CAD Assistant

**Comment by uPesy** [comment]
i have released a too buggy version  :/

**Comment by Bouni** [comment]
No big deal, hope I help with finding those bugs

**Comment by uPesy** [comment]
Sure, your help is very appreciated :)
I have already fix the closing bracket issue

**Comment by uPesy** [comment]
For the WRL issue, it's a bad edge effect of renaming a variable ...
