### ISSUE TITLE
Feature request: Add shortcut for easyeda2kicad command

### ISSUE THREAD

**Issue by Bouni** [uPesy/easyeda2kicad.py#39]
Maybe im just lazy but if possible it would be nice to have a shortcut for the `easyeda2kicad` command, `e2a` for example.

I'm not sure but I think that should be possible in the [setup.py](https://github.com/uPesy/easyeda2kicad.py/blob/master/setup.py#L27) like this:

```
entry_points={"console_scripts": [
   "easyeda2kicad = easyeda2kicad.__main__:main",
   "e2a= easyeda2kicad.__main__:main"
]},
```

**Comment by Bouni** [comment]
I'm not aware of an existing `e2a` command

**Comment by uPesy** [comment]
What are the meaning of `e2a` command ?
I think `e2k`is better for **e**asyeda**2k**icad
