### ISSUE TITLE
Missing Arc for C1222408

### ISSUE THREAD

**Issue by SnowballsChance** [uPesy/easyeda2kicad.py#62]
This capacitor's cathode is missing its arc. easyeda2kicad Version: 0.5.4

<img width="886" alt="Screen Shot 2022-06-29 at 21 44 55" src="https://user-images.githubusercontent.com/87108952/176428897-49513ef6-d683-43b9-b09b-c3fb9ad8e0dc.png">
<img width="381" alt="Screen Shot 2022-06-29 at 21 44 37" src="https://user-images.githubusercontent.com/87108952/176428911-7f448101-574b-4cb2-97fa-bd6fcd155cde.png">

**Comment by uPesy** [comment]
I don't have this bug on my machine : 
![image](https://user-images.githubusercontent.com/61392244/176847794-af34ac0a-98cb-4e7e-bb60-837c3659c2ed.png)

Maybe you should delete the symbol in your lib or use the parameters `--overwrite`
