### ISSUE TITLE
overwriting over 20 symbols on one file causes kicad to fail to load

### ISSUE THREAD

**Issue by wb1016** [uPesy/easyeda2kicad.py#64]
## expected behaviour
converted symbols are visible on kicad
## what actually happened
symbols fails to load when exeed 20 on a single file
## how to reproduce
add 20 symbols with command with --overwrite option
## how to go around
write to other file via --output option

**Comment by uPesy** [comment]
Thanks for submiting this issue !
Can you explain a little more about the bug ?
It happends when Kicad try to load the lib ?
Some screenshot will be really appreciated

**Comment by wb1016** [comment]
![1](https://user-images.githubusercontent.com/47267045/179374724-81c38a95-c636-479b-9e61-de429643a33a.PNG)
i have a file that has size about 59KB.
![2](https://user-images.githubusercontent.com/47267045/179374725-74e620c5-06e5-49b4-b0ed-42ceaf0af61d.PNG)
and i execute command, adding BMM150 just for example.
![3](https://user-images.githubusercontent.com/47267045/179374727-59e8a2e8-087f-4648-ba15-ba6abe49230c.PNG)
check file size has increased
![4](https://user-images.githubusercontent.com/47267045/179374728-58c784af-25a7-4d01-ab59-5c04f06cc0f8.PNG)
but symbol editor does not load changed library.
i tried deleting some symbols via symbol editor and re-executed the command, but it didnt help.

**Comment by uPesy** [comment]
Could you send me your easyeda2kicad.kicad_sym file to debug it ?
On Kicad 6, when you modify a library file (the tools do that), you have to close and re-open Kicad to see the change in the lib.
On v5 version, there is no this issue.

**Comment by wb1016** [comment]
[easyeda2kicad.zip](https://github.com/uPesy/easyeda2kicad.py/files/9138883/easyeda2kicad.zip)

**Comment by uPesy** [comment]
Thanks for the file, I will try to fix it after holidays.

**Comment by uPesy** [comment]
I have found the issue : it's because there is closing parenthesis in the middle of your file, at 1489 line.
```
      (pin unspecified line (at 3.81 10.16 270) (length 2.54)
        (name "7" (effects (font (size 1.27 1.27))))
        (number "7" (effects (font (size 1.27 1.27))))
      )
    )
  )
)
  (symbol "M1250RS-04P"
    (in_bom yes)
    (on_board yes)
    (property
      
```
