### ISSUE TITLE
installing through windows doesnt work

### ISSUE THREAD

**Issue by Cowh3adDK** [uPesy/easyeda2kicad.py#72]
after installing the package, running easyeda2kicad returns "easyeda2kicad : The term 'easyeda2kicad' is not recognized as the name of a cmdlet, function, script file, or operable
program."

**Comment by Cowh3adDK** [comment]
i think somewhere something gets confused if you have wsl ubuntu installed with python, uninstalled it and reinstalled python and easyeda2kicad on windows and it works now.

**Comment by Jackowski3k** [comment]
Will it work if you call it by "python -m easyeda2kicad"? Probably windows installation not providing the modules dir to system PATH?

**Comment by Cowh3adDK** [comment]
The problem was python wasnt added to my path, I had it installed from
docker I think, just uninstalled docker and python and installed python
manually.

**Comment by uPesy** [comment]
A clever way to install it without installing python is using the Kicad Command Prompt that have Python already install on it
