### ISSUE TITLE
Incompatibility with Pydantic-V2

### ISSUE THREAD

**Issue by SteamingCoax** [uPesy/easyeda2kicad.py#94]
I get the following error message when running:
<img width="1180" alt="Screenshot 2023-07-01 at 8 37 37 AM" src="https://github.com/uPesy/easyeda2kicad.py/assets/38991448/da05aac2-5ce4-4977-9c5a-7b6090990b71">

The program would need to be updated to properly work with pydantic-V2.

***Temporary Fix***:
Downgrade to the latest V1 Pydantic by uninstalling Pydantic-V2. 
`pip3 uninstall pydantic`

Then, install the latest V1 of Pydantic.
`pip3 install pydantic==1.10.7`

Hope this helps for the time being!

**Comment by uPesy** [comment]
Starting from v0.6.4, easyeda2kicad will use Pydantic v2. 
By updgrading the package, it should work correctly `pip install -U easyeda2kicad`.
